#!/bin/bash

OUTPUT=/data/mirror/www/size/index.html
for i in {2..-1}; do
    for d in /var/log/HOSTS/{ftp-osl.example.org,ftp-chi.example.org.ftp-nyc.example.org}; do
        LOG=$d/`date -d "$i days ago" "+%Y%m%d"`.mirrorlog
        if [ -e $LOG ]; then
            cat $LOG | /usr/local/sbin/mirror-size.pl
        elif [ -e $LOG.gz ]; then
            zcat $LOG | /usr/local/sbin/mirror-size.pl
        fi
    done
done

/usr/local/sbin/mirror-size-graph.sh
/usr/local/sbin/mirror-size-index.sh > /data/mirror/www/size/index.html
